name: Linux build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.compiler }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm, ubuntu-24.04, ubuntu-24.04-arm ]
        include:
          - os: ubuntu-22.04
            compiler: aarch64-linux-gnu-gcc
            pkgs: bmake crossbuild-essential-arm64
          - os: ubuntu-22.04-arm
            compiler: gcc
            pkgs: bmake
          - os: ubuntu-24.04
            compiler: aarch64-linux-gnu-gcc
            pkgs: bmake crossbuild-essential-arm64
          - os: ubuntu-24.04-arm
            compiler: gcc
            pkgs: bmake
    steps:
      - uses: actions/checkout@v3
      - name: install packages (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update --quiet || true
          sudo apt-get -yq --no-install-suggests --no-install-recommends install ${{ matrix.pkgs }}
      - name: make
        run: bmake CC=${{ matrix.compiler }}
      - name: run
        if: runner.arch == 'ARM64'
        run: ./arm64id
