name: Windows build

on: [push, pull_request]

jobs:
  build:
    name: Windows
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v6
      - name: install packages
        run: |
          choco install bmake || true
      - name: make
        run: bmake
      - name: run
        run: ./arm64id.exe
