name: Windows build

on: [push, pull_request]

jobs:
  build:
    name: Windows
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v6
      - name: Checkout err_windows
        uses: actions/checkout@v6
        with:
          repository: roydmerkel/err_windows
          path: ./err_windows
      - name: make
        run: clang --version && clang -O2 arm64id.c err_windows/err.c -I err_windows -o arm64id.exe
      - name: run
        run: gdb --version ; file arm64id.exe ; gdb --batch --command=run.gdb arm64id.exe
